### ISSUE TITLE
Can't link the en_core_web_md en

### ISSUE THREAD

**Issue by contactaman5** [fetchableai/example-rasa-chatbot#1]
While running this command
`python -m spacy link en_core_web_md en`

I'm getting this error

```
You do not have sufficient privilege to perform this operation.
✘ Couldn't link model to 'en'
Creating a symlink in spacy/data failed. Make sure you have the required
permissions and try re-running the command as admin, or use a virtualenv. You
can still import the model as a module and call its load() method, or create the
symlink manually.
C:\ProgramData\Anaconda3\envs\chatbot\lib\site-packages\en_core_web_md -->
C:\ProgramData\Anaconda3\envs\chatbot\lib\site-packages\spacy\data\en
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\site-packages\spacy\__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\site-packages\spacy\cli\link.py", line 65, in link
    symlink_to(link_path, model_path)
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\site-packages\spacy\compat.py", line 96, in symlink_to
    ["mklink", "/d", path2str(orig), path2str(dest)], shell=True
  File "C:\ProgramData\Anaconda3\envs\chatbot\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mklink', '/d', 'C:\\ProgramData\\Anaconda3\\envs\\chatbot\\lib\\site-packages\\spacy\\data\\en', 'C:\\ProgramData\\Anaconda3\\envs\\chatbot\\lib\\site-packages\\en_core_web_md']' returned non-zero exit status 1.
```

**Comment by rakib06** [comment]
facing the same problem 
![image](https://user-images.githubusercontent.com/34921424/103027852-d533bc00-4580-11eb-9a47-f54e1652608e.png)

**Comment by rakib06** [comment]
Open cmd as administrator 
and then .. 
![image](https://user-images.githubusercontent.com/34921424/103028188-6c990f00-4581-11eb-8533-4a41203d37b6.png)
**Solved**
